---
env:
  node: true
  es6: true
extends: eslint:recommended
parser: "@typescript-eslint/parser"
parserOptions:
  sourceType: module
plugins:
  - "@typescript-eslint"
rules:
  require-jsdoc:
    - error
    - require:
        ClassDeclaration: true
        FunctionDeclaration: true
        MethodDefinition: true
  valid-jsdoc:
    - error
    - matchDescription: ".+"
      requireParamDescription: true
      requireParamType: true
      requireReturnType: true
